import 'global.dart';

enum payments { Zero, First, Second, Third, Fourth }
const Map<payments, String> paymentsValues = {
  payments.Zero: "No Payment",
  payments.First: "First",
  payments.Second: "Second",
  payments.Third: "Third",
  payments.Fourth: "Fourth",
};
enum paymentDue {
  zero,
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
  eleven,
  twelve,
  thirteen,
  fourteen,
  fifteen,
  sixteen,
  seventeen,
  eighteen,
  nineteen,
  twenty,
  twentyone,
  twentytwo,
  twentythree,
  twentyfour,
  twentyfive,
  twentysix,
  twentyseven,
  twentyeight,
  twentynine,
  thirty,
  thirtyone,
}
const Map<paymentDue, String> paymentDueValues = {
  paymentDue.zero: 'No dues',
  paymentDue.one: "Due next in One day",
  paymentDue.two: "Due next in Two days",
  paymentDue.three: "Due next in Three days",
  paymentDue.four: "Due next in Four days",
  paymentDue.five: "Due next in Five days",
  paymentDue.six: "Due next in Six days",
  paymentDue.seven: "Due next in Seven days",
  paymentDue.eight: "Due next in Eight days",
  paymentDue.nine: "Due next in Nine days",
  paymentDue.ten: "Due next in Ten days",
  paymentDue.eleven: "Due next in Eleven days",
  paymentDue.twelve: "Due next in Twelve days",
  paymentDue.thirteen: "Due next in Thirteen days",
  paymentDue.fourteen: "Due next in Fourteen days",
  paymentDue.fifteen: "Due next in Fifteen days",
  paymentDue.sixteen: "Due next in Sixteen days",
  paymentDue.seventeen: "Due next in Seventeen days",
  paymentDue.eighteen: "Due next in Eighteen days",
  paymentDue.nineteen: "Due next in Nineteen days",
  paymentDue.twenty: "Due next in Twenty days",
  paymentDue.twentyone: "Due next in TwentyOne days",
  paymentDue.twentytwo: "Due next in TwentyTwo days",
  paymentDue.twentythree: "Due next in TwentyThree days",
  paymentDue.twentyfour: "Due next in TwentyFour days",
  paymentDue.twentyfive: "Due next in TwentyFive days",
  paymentDue.twentysix: "Due next in TwentySix days",
  paymentDue.twentyseven: "Due next in TwentySeven days",
  paymentDue.twentyeight: "Due next in TwentyEight days",
  paymentDue.twentynine: "Due next in TwentyNine days",
  paymentDue.thirty: "Due next in Thirty days",
  paymentDue.thirtyone: "Due next in ThirtyOne days",
};
Map<String, String> paymentTypeToImage = {
  Cards.masterCard: 'assets/cards/master_card.png',
  Cards.master: 'assets/cards/master_card.png',
  Cards.visaCard: 'assets/cards/visa_card.png',
  Cards.visa: 'assets/cards/visa_card.png',
};

enum installmentNumbers { First, Second, Third, Fourth, Full }
const Map<installmentNumbers, String> installmentValues = {
  installmentNumbers.Full: "full",
  installmentNumbers.First: "1",
  installmentNumbers.Second: "2",
  installmentNumbers.Third: "3",
  installmentNumbers.Fourth: "4",
};
